# Generated by Django 2.2.14 on 2020-09-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juice_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='rate',
        ),
    ]
